\input texinfo
@setfilename mageec.info
@afourpaper
@settitle MAGEEC
@paragraphindent 0

@copying
This manual is for MAGEEC.

Copyright @copyright{} 2013, 2014 Embecosm Limited and University of Bristol.
@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts. A copy of the license is included in the section entitled
``GNU Free Documentation License''.
@end quotation
@end copying

@titlepage
@title MAGEEC
@subtitle MAchine Guided Energy Efficient Compilation
@author Simon Cook
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@node Top
@top Scope of this Document
This document is the user guide for the MAGEEC @emph{MAchine Guided Energy
Efficient Compilation} project.

@menu
* Building MAGEEC::
* GCC Plugin::
* GNU Free Documentation License::
@end menu

@node Building MAGEEC
@chapter Building MAGEEC
MAGEEC uses a standard GNU Autotools based build and installation system.

The build and installation can be configured using the @command{configure}
script in the main source directory. The build should take place in a directory
separate to the source.

@example
tar xjf mageec-@value{VERSION}.tar.bz2
mkdir build-mageec
cd build-mageec
../mageec-@value{VERSION}/configure ...
@end example

Available configuration options can be found by providing @code{--help} to
@command{configure}. The most useful of these is the @code{--prefix=PREFIX}
option which is used to set the installation location; tools will be installed
into @code{PREFIX/bin} and libraries installed in @code{PREFIX/lib}.

Once configured, MAGEEC can be built using:

@example
make all
@end example

It can then be installed using:

@example
make install
@end example

@node GCC Plugin
@chapter GCC Plugin

@node GNU Free Documentation License
@chapter GNU Free Documentation License
@include fdl-1.3.texi

@bye
